pipeline {
    agent any

    options {
        // Keep last 30 builds
        buildDiscarder(logRotator(numToKeepStr: '30'))
        
        // Add timestamps to console output
        timestamps()
        
        // Timeout for the entire pipeline
        timeout(time: 1, unit: 'HOURS')
    }

    environment {
        // Node.js environment variables
        NODE_ENV = 'test'
        PATH = "${tool 'Node.js 18.x'}/bin:${env.PATH}"
    }

    stages {
        stage('Checkout') {
            steps {
                echo '========== Checking out code =========='
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                echo '========== Installing Node dependencies =========='
                bat '''
                    echo Checking Node.js version
                    node --version
                    
                    echo Checking npm version
                    npm --version
                    
                    echo Installing dependencies
                    npm install
                '''
            }
        }

        stage('Install Playwright Browsers') {
            steps {
                echo '========== Installing Playwright browsers =========='
                bat '''
                    echo Installing Playwright browsers
                    npm exec playwright install chromium
                '''
            }
        }

        stage('Run UI Tests') {
            steps {
                echo '========== Running UI Tests =========='
                bat '''
                    echo Running UI tests
                    npm run test:ui
                '''
            }
        }

        stage('Run API Tests') {
            steps {
                echo '========== Running API Tests =========='
                bat '''
                    echo Running API tests
                    npm run test:api
                '''
            }
        }

        stage('Generate Reports') {
            steps {
                echo '========== Generating test reports =========='
                // Reports are auto-generated by Playwright
                script {
                    echo "Test reports generated successfully"
                }
            }
        }
    }

    post {
        always {
            echo '========== Publishing test results =========='
            
            // Publish JUnit XML results
            junit testResults: '**/test-results/junit.xml', 
                  allowEmptyResults: true,
                  skipPublishingChecks: true
            
            // Archive Playwright HTML report
            archiveArtifacts artifacts: 'playwright-report/**/*',
                             allowEmptyArchive: true
            
            // Archive test results
            archiveArtifacts artifacts: 'test-results/**/*',
                             allowEmptyArchive: true
            
            // Clean workspace
            deleteDir()
        }

        success {
            echo '========== Build Successful =========='
            echo 'All tests passed successfully!'
        }

        failure {
            echo '========== Build Failed =========='
            echo 'One or more tests failed. Check the reports above.'
        }

        unstable {
            echo '========== Build Unstable =========='
            echo 'Some tests may have failed.'
        }
    }
}
